### ISSUE TITLE
requires_python column too short

### ISSUE THREAD

**Issue by bennuttall** [piwheels/piwheels#327]
```
Oct 28 18:53:24 piwheels piw-master[2658]: master.the_oracle_2: Error handling db request: LOGBUILD
Oct 28 18:53:24 piwheels piw-master[2658]: master.slave_driver: unhandled exception in <SlaveDriver(Thread-10, started 2861548608)>                                                                           
Oct 28 18:53:24 piwheels piw-master[2658]: Traceback (most recent call last):
Oct 28 18:53:24 piwheels piw-master[2658]:   File "/usr/local/lib/python3.7/dist-packages/piwheels/tasks.py", line 310, in run                                                                                
Oct 28 18:53:24 piwheels piw-master[2658]:     self.poll()
Oct 28 18:53:24 piwheels piw-master[2658]:   File "/usr/local/lib/python3.7/dist-packages/piwheels/tasks.py", line 289, in poll                                                                               
Oct 28 18:53:24 piwheels piw-master[2658]:     self.sockets[queue](queue)
Oct 28 18:53:24 piwheels piw-master[2658]:   File "/usr/local/lib/python3.7/dist-packages/piwheels/master/slave_driver.py", line 332, in handle_slave                                                         
Oct 28 18:53:24 piwheels piw-master[2658]:     msg, data = handler(slave)
Oct 28 18:53:24 piwheels piw-master[2658]:   File "/usr/local/lib/python3.7/dist-packages/piwheels/master/slave_driver.py", line 528, in do_sent                                                              
Oct 28 18:53:24 piwheels piw-master[2658]:     self.db.log_build(slave.build)
Oct 28 18:53:24 piwheels piw-master[2658]:   File "/usr/local/lib/python3.7/dist-packages/piwheels/master/the_oracle.py", line 545, in log_build                                                              
Oct 28 18:53:24 piwheels piw-master[2658]:     build_id = self._execute('LOGBUILD', build.as_message())                                                                                                       
Oct 28 18:53:24 piwheels piw-master[2658]:   File "/usr/local/lib/python3.7/dist-packages/piwheels/master/the_oracle.py", line 419, in _execute                                                               
Oct 28 18:53:24 piwheels piw-master[2658]:     raise IOError(result)
Oct 28 18:53:24 piwheels piw-master[2658]: OSError: (psycopg2.DataError) value too long for type character varying(100)                                                                                       
Oct 28 18:53:24 piwheels piw-master[2658]: [SQL: VALUES (log_build_success(%s, %s, %s, %s, %s, CAST(%s AS files ARRAY), CAST(%s AS dependencies ARRAY)))]                                                     
Oct 28 18:53:24 piwheels piw-master[2658]: [parameters: ('encord-active', '0.1.0', 94, datetime.timedelta(seconds=11, microseconds=792398), 'cp39', [('encord_active-0.1.0-py3-none-any.whl', None, 68529, 'e373f9cf0e59030c4c4cb35f2d2a587a6073a62006b92a6d4361396194461f22', 'encord_active', '0.1.0', 'py3', 'none', 'any', '>=3.9, !=2.7.*, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*, !=3.4.*, !=3.5.*, !=3.6.*, !=3.7.*, !=3.8.*, !=3.11.*')], [])]
Oct 28 18:53:24 piwheels piw-master[2658]: (Background on this error at: http://sqlalche.me/e/9h9h)
```

**Comment by bennuttall** [comment]
Done in https://github.com/piwheels/piwheels/commit/16d961ee355266c1139a3c9b8538a3c230a48b95
