### ISSUE TITLE
log_search crashes master on bad ip address

### ISSUE THREAD

**Issue by bennuttall** [piwheels/piwheels#341]
```
Dec 20 02:53:08 piwheels piw-master[10789]: master.the_oracle_3: Error handling db request: LOGSEARCH
Dec 20 02:53:08 piwheels piw-master[10789]: master.lumberjack: unhandled exception in <Lumberjack(Thread-5, started 2966418496)>                                                                                                             
Dec 20 02:53:08 piwheels piw-master[10789]: Traceback (most recent call last):
Dec 20 02:53:08 piwheels piw-master[10789]:   File "/usr/local/lib/python3.7/dist-packages/piwheels/tasks.py", line 310, in run                                                                                                              
Dec 20 02:53:08 piwheels piw-master[10789]:     self.poll()
Dec 20 02:53:08 piwheels piw-master[10789]:   File "/usr/local/lib/python3.7/dist-packages/piwheels/tasks.py", line 289, in poll                                                                                                             
Dec 20 02:53:08 piwheels piw-master[10789]:     self.sockets[queue](queue)
Dec 20 02:53:08 piwheels piw-master[10789]:   File "/usr/local/lib/python3.7/dist-packages/piwheels/master/lumberjack.py", line 97, in handle_log                                                                                            
Dec 20 02:53:08 piwheels piw-master[10789]:     handler(state_cls.from_message(data))
Dec 20 02:53:08 piwheels piw-master[10789]:   File "/usr/local/lib/python3.7/dist-packages/piwheels/master/the_oracle.py", line 521, in log_search                                                                                           
Dec 20 02:53:08 piwheels piw-master[10789]:     self._execute('LOGSEARCH', search.as_message())
Dec 20 02:53:08 piwheels piw-master[10789]:   File "/usr/local/lib/python3.7/dist-packages/piwheels/master/the_oracle.py", line 419, in _execute                                                                                             
Dec 20 02:53:08 piwheels piw-master[10789]:     raise IOError(result)
Dec 20 02:53:08 piwheels piw-master[10789]: OSError: (psycopg2.DataError) invalid input syntax for type inet: "ea5"
Dec 20 02:53:08 piwheels piw-master[10789]: LINE 1: VALUES (log_search('enum34', 'ea5', '2023-12-20T02:53:07'::t...
Dec 20 02:53:08 piwheels piw-master[10789]:                                      ^
Dec 20 02:53:08 piwheels piw-master[10789]: [SQL: VALUES (log_search(%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s))]                                                                                                                   
Dec 20 02:53:08 piwheels piw-master[10789]: [parameters: ('enum34', 'ea5', datetime.datetime(2023, 12, 20, 2, 53, 7), 'armv7l', 'Raspbian GNU/Linux', '11', 'Linux', '6.1.21-v7+', 'CPython', '3.9.2', 'pip', '23.3.2', '68.2.2')]
```

**Comment by bennuttall** [comment]
Fixed by https://github.com/piwheels/piwheels/commit/6cdca6692396e54b1bb2268e9fab38e0976beb5b
